---
title: "Bookmarks of Inspiration"
subtitle: "Curated Internet finds for curious minds"
title-block-banner: true
format:
  html:
    toc: true
    toc-expand: 3
description: "Welcome to my collection of favorite corners of the internet—a curated list of sites I find fascinating, entertaining, and worth sharing with the world."
---

## Free and liberated ebooks, carefully produced for the true book lover

From the site:

> Standard Ebooks is a volunteer-driven project that produces new editions of public domain ebooks that are lovingly formatted, open source, free of U.S. copyright restrictions, and free of cost.
>
> Ebook projects like Project Gutenberg transcribe ebooks and make them available for the widest number of reading devices. Standard Ebooks takes ebooks from sources like Project Gutenberg, formats and typesets them using a carefully designed and professional-grade style manual, fully proofreads and corrects them, and then builds them to create a new edition that takes advantage of state-of-the-art ereader and browser technology.
>
> Standard Ebooks aren’t just a beautiful addition to your digital library—they’re a high quality standard to build your own ebooks on.

👉 [Browse](https://standardebooks.org/)

