-- Generate Quarto series pages before the website render.
--
-- Source article layout is NEVER modified:
--   longforms/<article-slug>/index.qmd
--   posts/<article-slug>/index.qmd
--
-- Generated pages are written only to:
--   series.qmd
--   series/<series-slug>/index.qmd
--
-- Run automatically by Quarto through project.pre-render.

local sep = package.config:sub(1, 1)
local GENERATED_MARKER = "<!-- generated by _scripts/generate-series.lua; do not edit -->"

local function trim(value)
  value = value or ""
  return (value:gsub("^%s+", ""):gsub("%s+$", ""))
end

local function join_fs(...)
  local parts = { ... }
  return table.concat(parts, sep)
end

local function to_web_path(path)
  return (path or ""):gsub("\\", "/")
end

local function file_exists(path)
  local f = io.open(path, "r")
  if f then
    f:close()
    return true
  end
  return false
end

local function is_directory(path)
  local ok, entries = pcall(pandoc.system.list_directory, path)
  return ok and type(entries) == "table"
end

local function read_file(path)
  local f, err = io.open(path, "r")
  if not f then
    error("series generator: cannot read " .. path .. ": " .. tostring(err))
  end
  local content = f:read("*a")
  f:close()
  return content
end

local function write_file(path, content)
  local f, err = io.open(path, "w")
  if not f then
    error("series generator: cannot write " .. path .. ": " .. tostring(err))
  end
  f:write(content)
  f:close()
end

local function ensure_directory(path)
  if not is_directory(path) then
    pandoc.system.make_directory(path, true)
  end
end

local function extract_yaml(content)
  content = (content or ""):gsub("\r\n", "\n"):gsub("\r", "\n")
  if not content:match("^%-%-%-\n") then
    return nil
  end
  return content:match("^%-%-%-\n(.-)\n%-%-%-%s*\n")
end

local function parse_metadata(path)
  local content = read_file(path)
  local yaml = extract_yaml(content)
  if not yaml then
    return nil
  end

  local ok, doc = pcall(pandoc.read, "---\n" .. yaml .. "\n---\n", "markdown")
  if not ok or not doc then
    error("series generator: cannot parse YAML in " .. path)
  end

  local meta = doc.meta or {}
  local draft = pandoc.text.lower(trim(pandoc.utils.stringify(meta.draft or "")))
  local is_draft = draft == "true" or draft == "yes" or draft == "1"

  local series = nil
  if meta.series ~= nil then
    local meta_type = pandoc.utils.type(meta.series)
    if meta_type == "MetaList" or meta_type == "List" or meta_type == "MetaMap" then
      error("series generator: 'series' must be one scalar title in " .. path)
    end
    series = trim(pandoc.utils.stringify(meta.series))
    if series == "" then
      series = nil
    end
  end

  local date_modified = trim(pandoc.utils.stringify(meta["date-modified"] or ""))
  local normalized_date = nil
  if date_modified ~= "" then
    normalized_date = pandoc.utils.normalize_date(date_modified)
    if not normalized_date then
      error("series generator: invalid date-modified '" .. date_modified .. "' in " .. path)
    end
  end

  return {
    draft = is_draft,
    series = series,
    date_modified = date_modified,
    normalized_date = normalized_date,
  }
end

local skipped_directories = {
  [".git"] = true,
  [".quarto"] = true,
  ["_freeze"] = true,
  ["_site"] = true,
  ["docs"] = true,
  ["node_modules"] = true,
}

local function collect_article_files(project_root, collection)
  local collection_root = join_fs(project_root, collection)
  local files = {}

  local function walk(directory, relative_directory)
    local ok, entries = pcall(pandoc.system.list_directory, directory)
    if not ok or type(entries) ~= "table" then
      return
    end

    table.sort(entries)

    for _, entry in ipairs(entries) do
      if entry ~= "." and entry ~= ".." and not skipped_directories[entry] then
        local path = join_fs(directory, entry)
        local rel = relative_directory == "" and entry or (relative_directory .. "/" .. entry)

        if is_directory(path) then
          walk(path, rel)
        elseif entry == "index.qmd" then
          table.insert(files, {
            path = path,
            rel = collection .. "/" .. rel,
          })
        end
      end
    end
  end

  if is_directory(collection_root) then
    walk(collection_root, "")
  end

  return files
end

local function slugify(title)
  local slug = pandoc.text.lower(trim(title or ""))
  slug = slug:gsub("['’]", "")
  slug = slug:gsub("[^a-z0-9]+", "-")
  slug = slug:gsub("%-+", "-")
  slug = slug:gsub("^%-", ""):gsub("%-$", "")
  if slug == "" then
    error("series generator: cannot derive a URL slug from series title '" .. tostring(title) .. "'")
  end
  return slug
end

local function yaml_quote(value)
  value = tostring(value or "")
  value = value:gsub("\\", "\\\\")
  value = value:gsub('"', '\\"')
  value = value:gsub("\r", " "):gsub("\n", " ")
  return '"' .. value .. '"'
end

local function html_escape(value)
  value = tostring(value or "")
  value = value:gsub("&", "&amp;")
  value = value:gsub("<", "&lt;")
  value = value:gsub(">", "&gt;")
  value = value:gsub('"', "&quot;")
  return value
end

local function replace_literal(text, needle, replacement)
  local pattern = needle:gsub("([^%w])", "%%%1")
  return (text:gsub(pattern, function() return replacement end))
end

local function scan_series(project_root)
  local groups = {}

  for _, collection in ipairs({ "longforms", "posts" }) do
    for _, article in ipairs(collect_article_files(project_root, collection)) do
      local meta = parse_metadata(article.path)
      if meta and not meta.draft and meta.series then
        if not meta.normalized_date then
          error(
            "series generator: article with series '" .. meta.series ..
            "' must define date-modified: " .. article.rel
          )
        end

        local group = groups[meta.series]
        if not group then
          group = {
            title = meta.series,
            slug = slugify(meta.series),
            latest = meta.normalized_date,
            articles = {},
          }
          groups[meta.series] = group
        end

        if meta.normalized_date > group.latest then
          group.latest = meta.normalized_date
        end

        table.insert(group.articles, {
          rel = to_web_path(article.rel),
          date_modified = meta.normalized_date,
        })
      end
    end
  end

  local by_slug = {}
  local series = {}
  for _, group in pairs(groups) do
    local existing = by_slug[group.slug]
    if existing and existing ~= group.title then
      error(
        "series generator: series titles '" .. existing .. "' and '" .. group.title ..
        "' both map to URL slug '" .. group.slug .. "'. Rename one series."
      )
    end
    by_slug[group.slug] = group.title

    table.sort(group.articles, function(a, b)
      if a.date_modified ~= b.date_modified then
        return a.date_modified > b.date_modified
      end
      return a.rel < b.rel
    end)
    table.insert(series, group)
  end

  table.sort(series, function(a, b)
    if a.latest ~= b.latest then
      return a.latest > b.latest
    end
    return a.title < b.title
  end)

  return series
end

local function listing_contents(articles, prefix)
  local lines = {}
  prefix = prefix or ""
  for _, article in ipairs(articles) do
    table.insert(lines, "    - " .. yaml_quote(prefix .. article.rel))
  end
  return table.concat(lines, "\n")
end

local function generate_individual_pages(project_root, series)
  local template_path = join_fs(project_root, "_templates", "series-template.qmd")
  local template = read_file(template_path)
  local series_root = join_fs(project_root, "series")
  ensure_directory(series_root)

  local active = {}

  for _, group in ipairs(series) do
    active[group.slug] = true
    local directory = join_fs(series_root, group.slug)
    ensure_directory(directory)

    local rendered = template
    rendered = replace_literal(rendered, "{{SERIES_TITLE}}", yaml_quote(group.title))
    rendered = replace_literal(rendered, "{{SERIES_CONTENTS}}", listing_contents(group.articles, "../../"))
    rendered = GENERATED_MARKER .. "\n" .. rendered

    write_file(join_fs(directory, "index.qmd"), rendered)
  end

  -- Delete only stale directories that were generated by this script.
  local ok, entries = pcall(pandoc.system.list_directory, series_root)
  if ok and type(entries) == "table" then
    for _, entry in ipairs(entries) do
      local directory = join_fs(series_root, entry)
      local index_path = join_fs(directory, "index.qmd")
      if is_directory(directory) and not active[entry] and file_exists(index_path) then
        local content = read_file(index_path)
        if content:find(GENERATED_MARKER, 1, true) then
          pandoc.system.remove_directory(directory, true)
        end
      end
    end
  end
end

local function append_listing_yaml(lines, group)
  local id = "series-" .. group.slug
  table.insert(lines, "  - id: " .. id)
  table.insert(lines, "    contents:")
  for _, article in ipairs(group.articles) do
    table.insert(lines, "      - " .. yaml_quote(article.rel))
  end
  table.insert(lines, "    page-size: 3")
  table.insert(lines, "    sort: \"date-modified desc\"")
  table.insert(lines, "    type: grid")
  table.insert(lines, "    fields: [image, title, subtitle, date-modified]")
  table.insert(lines, "    sort-ui: false")
  table.insert(lines, "    filter-ui: false")
  table.insert(lines, "    categories: false")
  table.insert(lines, "    max-description-length: 300")
end

local function generate_series_index(project_root, series)
  local lines = {
    GENERATED_MARKER,
    "---",
    "title: \"Series\"",
    "subtitle: \"Article sequences that follow a subject as it develops over time.\"",
    "page-layout: full",
    "title-block-banner: true",
    "sidebar: false",
  }

  if #series > 0 then
    table.insert(lines, "listing:")
    for _, group in ipairs(series) do
      append_listing_yaml(lines, group)
    end
  end

  table.insert(lines, "---")
  table.insert(lines, "")

  if #series == 0 then
    table.insert(lines, "No series have been published yet.")
  else
    for _, group in ipairs(series) do
      table.insert(lines, '<section class="series-overview-row">')
      table.insert(lines,
        '<h2><a href="/series/' .. group.slug .. '/">' .. html_escape(group.title) .. '</a></h2>'
      )
      local noun = #group.articles == 1 and "article" or "articles"
      table.insert(lines,
        '<p class="text-muted">Last updated ' .. html_escape(group.latest) ..
        ' · ' .. tostring(#group.articles) .. ' ' .. noun .. '</p>'
      )
      table.insert(lines, "")
      table.insert(lines, "::: {#series-" .. group.slug .. "}")
      table.insert(lines, ":::")
      table.insert(lines, "")
      table.insert(lines, "</section>")
      table.insert(lines, "")
      table.insert(lines, '<hr class="my-5">')
      table.insert(lines, "")
    end
  end

  write_file(join_fs(project_root, "series.qmd"), table.concat(lines, "\n") .. "\n")
end

local function main()
  local project_root = pandoc.system.get_working_directory()
  local series = scan_series(project_root)
  generate_individual_pages(project_root, series)
  generate_series_index(project_root, series)

  io.stdout:write(
    string.format("series generator: %d series generated; article source paths unchanged\n", #series)
  )
end

main()
